const toggle=document.getElementById('themeToggle');
const root=document.documentElement;
const themeColor=document.querySelector('meta[name="theme-color"]');
const languageButtons=document.querySelectorAll('.language-button');
const translations={fr:{
'nav.aria':'Navigation principale','nav.about':'À propos','nav.projects':'Projets','nav.writing':'Écriture','nav.services':'Anglais','nav.contact':'Contact','theme.dark':'Sombre','theme.light':'Clair',
'meta.title':'Aliou Ba | Ingénieur logiciel','hero.eyebrow':'Génie logiciel · Cybersécurité · Cloud','hero.title':'Je conçois des logiciels, j’explore la cybersécurité et je rends les sujets techniques complexes plus simples.','hero.intro':'Je suis Aliou Ba, élève-ingénieur en informatique et télécommunications à l’Institut Polytechnique de Saint-Louis. Je construis des produits pratiques et j’étudie les systèmes backend et cloud sécurisés.','hero.projects':'Voir les projets','hero.services':'Services en anglais','hero.more':'En savoir plus',
'sections.about':'01 / À propos','about.p1':'Je travaille dans le développement backend, les réseaux, la cybersécurité et le cloud. Mon orientation actuelle se situe à l’intersection du <strong>développement backend + sécurité applicative + cloud + DevSecOps</strong>.','about.p2':'J’enseigne également la technologie, j’écris du contenu éducatif et je construis des produits autour de problèmes qui m’intéressent.',
'sections.projects':'02 / Projets sélectionnés','projects.zikrou.text':'Une application mobile en production pour écouter des Zikr et Waxtanes. J’ai travaillé sur le backend, les API, la base de données, l’authentification, l’infrastructure et le déploiement.','projects.academy.text':'Une plateforme d’apprentissage de l’anglais actuellement en développement, conçue pour toute personne souhaitant apprendre l’anglais, évaluer son niveau, pratiquer ou préparer des examens comme le TOEIC.','projects.microservices.text':'Un projet technique consacré à l’architecture backend sécurisée, à l’authentification et à la communication entre services.','projects.security.text':'Un environnement pratique pour étudier la sécurité des applications web, la sécurité des API et les vulnérabilités courantes de l’OWASP.','projects.incubator.title':'Incubateur automatique d’œufs','projects.incubator.text':'Un incubateur automatisé conçu pour maintenir une température et une humidité adaptées pendant tout le cycle d’incubation et retourner automatiquement les œufs grâce à un système motorisé. Le projet a été réalisé avec un camarade dans le cadre d’un projet pratique d’ingénierie.','projects.view':'Voir le projet','projects.visit':'Visiter la plateforme',
'sections.writing':'03 / Écriture & éducation','writing.intro':'J’écris sur la technologie, l’anglais, la communication et des idées pratiques. Sur Medium, je partage des conseils en anglais, je résume les livres que je lis et j’explique des concepts techniques de manière simple et accessible.','writing.book':'Éducation en anglais · Livre · Plus de 1 000 ventes dans le monde','writing.medium':'Écriture technique · Résumés de livres · Anglais & technologie','writing.it':'Anglais technique · Éducation','writing.security':'Sécurité · Technologie',
'sections.experience':'04 / Expérience','experience.huawei':'Ingénierie des solutions et IP Datacom · août 2024 à octobre 2024 · Routage · Switching · Dépannage','experience.academy':'Fondateur · Éducation en anglais · décembre 2024 à aujourd’hui · Plus de 50 apprenants formés',
'sections.contact':'05 / Contact','contact.title':'Construisons quelque chose d’utile.','footer.right':'Réalisé en HTML, CSS & JavaScript',
'services.eyebrow':'Anglais · Cours · Coaching · Consultation','services.title':'Un accompagnement pratique en anglais, adapté à vos besoins réels.','services.intro':'Que vous souhaitiez parler avec plus d’assurance, mieux comprendre l’anglais, améliorer votre expression écrite, préparer une situation professionnelle ou simplement savoir quoi travailler ensuite, nous partons de votre situation pour construire la suite.','services.request':'Demander un accompagnement','services.offers.label':'01 / Services','services.individual.title':'Cours d’anglais individuels','services.individual.text':'Des séances personnalisées centrées sur le speaking, listening, reading et writing, selon ce que vous souhaitez améliorer.','services.group.title':'Cours en petit groupe','services.group.text':'Des séances pratiques pour des groupes de 3 à 4 personnes maximum, avec une vraie place pour la conversation et la pratique.','services.consult.title':'Consultation d’une heure','services.consult.text':'Une séance ciblée pour évaluer votre situation, identifier ce qui vous bloque, répondre à vos questions et repartir avec un plan d’action clair pour améliorer votre anglais.','services.guidance.title':'Orientation & coaching en anglais','services.guidance.text':'Des conseils sur des problèmes précis : aisance à l’oral, difficultés de compréhension, écriture, anglais professionnel, entretiens, communication ou choix de la prochaine étape.','services.approach.label':'02 / Approche','services.approach.text':'Aucun parcours scolaire particulier n’est requis. L’objectif est de comprendre où vous en êtes, ce que vous voulez atteindre et ce qui vous bloque, puis de travailler l’anglais réellement utile pour vous.','services.process.assess':'Évaluer','services.process.assess.text':'Comprendre votre niveau et vos difficultés.','services.process.focus':'Cibler','services.process.focus.text':'Identifier les compétences et situations prioritaires.','services.process.action':'Agir','services.process.action.text':'Repartir avec des conseils pratiques et un plan clair.','services.request.label':'03 / Demande','services.request.title':'Dites-moi ce dont vous avez besoin.','services.request.intro':'Choisissez le type d’accompagnement qui vous intéresse et donnez-moi suffisamment de contexte pour comprendre votre situation.','services.direct':'Ou contactez-moi directement :','form.name':'Nom complet','form.email':'Email','form.phone':'Numéro WhatsApp','form.profile':'Votre profil','form.select':'Sélectionner','form.service':'Que recherchez-vous ?','form.domain':'Votre domaine / secteur','form.goals':'Que souhaitez-vous améliorer ou résoudre ?','form.submit':'Envoyer la demande'
}};

document.querySelectorAll('[data-i18n]').forEach(e=>e.dataset.enText=e.innerHTML);
document.querySelectorAll('[data-i18n-aria]').forEach(e=>e.dataset.enAria=e.getAttribute('aria-label'));
function setLanguage(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;e.innerHTML=lang==='fr'&&translations.fr[k]?translations.fr[k]:e.dataset.enText});document.querySelectorAll('[data-i18n-aria]').forEach(e=>{const k=e.dataset.i18nAria;e.setAttribute('aria-label',lang==='fr'&&translations.fr[k]?translations.fr[k]:e.dataset.enAria)});languageButtons.forEach(b=>{const active=b.dataset.lang===lang;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const title=document.querySelector('title[data-i18n]');if(title)document.title=lang==='fr'&&translations.fr['meta.title']?translations.fr['meta.title']:title.dataset.enText;localStorage.setItem('language',lang)}
function updateThemeButton(){const isDark=root.dataset.theme==='dark';toggle.setAttribute('aria-pressed',String(isDark));toggle.setAttribute('aria-label',isDark?'Switch to light mode':'Switch to dark mode');const label=toggle.querySelector('.theme-label');if(label){const key=isDark?'theme.light':'theme.dark';label.innerHTML=key==='theme.light'?'Light':'Dark';if(document.documentElement.lang==='fr')label.innerHTML=isDark?'Clair':'Sombre'}if(themeColor)themeColor.setAttribute('content',isDark?'#111315':'#fbfbf9')}
updateThemeButton();toggle.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('theme',root.dataset.theme);updateThemeButton()});languageButtons.forEach(b=>b.addEventListener('click',()=>{setLanguage(b.dataset.lang);updateThemeButton()}));setLanguage(localStorage.getItem('language')||'en');