const toggle=document.getElementById('themeToggle');
const root=document.documentElement;
const themeColor=document.querySelector('meta[name="theme-color"]');
const languageButtons=document.querySelectorAll('.language-button');
const translations={fr:{
'nav.about':'À propos','nav.projects':'Projets','nav.writing':'Écriture','nav.services':'Anglais','nav.contact':'Contact',
'hero.eyebrow':'Génie logiciel · Cybersécurité · Cloud','hero.title':'Je conçois des logiciels, j’explore la cybersécurité et je rends les sujets techniques complexes plus simples.',
'hero.intro':'Je suis Aliou Ba, élève-ingénieur en informatique et télécommunications à l’Institut Polytechnique de Saint-Louis. Je construis des produits pratiques et j’étudie les systèmes backend et cloud sécurisés.',
'hero.projects':'Voir les projets','hero.services':'Services en anglais','hero.more':'En savoir plus',
'services.eyebrow':'Anglais · Cours · Coaching · Consultation','services.title':'Un accompagnement pratique en anglais, adapté à vos besoins réels.','services.intro':'Que vous souhaitiez parler avec plus d’assurance, mieux comprendre l’anglais, améliorer votre expression écrite, préparer une situation professionnelle ou simplement savoir quoi travailler ensuite, nous partons de votre situation pour construire la suite.','services.request':'Demander un accompagnement',
'services.offers.label':'01 / Services','services.individual.title':'Cours d’anglais individuels','services.individual.text':'Des séances personnalisées centrées sur le speaking, listening, reading et writing, selon ce que vous souhaitez améliorer.','services.group.title':'Cours en petit groupe','services.group.text':'Des séances pratiques pour des groupes de 3 à 4 personnes maximum, avec une vraie place pour la conversation et la pratique.','services.consult.title':'Consultation d’une heure','services.consult.text':'Une séance ciblée pour évaluer votre situation, identifier ce qui vous bloque, répondre à vos questions et repartir avec un plan d’action clair pour améliorer votre anglais.','services.guidance.title':'Orientation & coaching en anglais','services.guidance.text':'Des conseils sur des problèmes précis : aisance à l’oral, difficultés de compréhension, écriture, anglais professionnel, entretiens, communication ou choix de la prochaine étape.','services.approach.label':'02 / Approche','services.approach.text':'Aucun parcours scolaire particulier n’est requis. L’objectif est de comprendre où vous en êtes, ce que vous voulez atteindre et ce qui vous bloque, puis de travailler l’anglais réellement utile pour vous.','services.process.assess':'Évaluer','services.process.assess.text':'Comprendre votre niveau et vos difficultés.','services.process.focus':'Cibler','services.process.focus.text':'Identifier les compétences et situations prioritaires.','services.process.action':'Agir','services.process.action.text':'Repartir avec des conseils pratiques et un plan clair.','services.request.label':'03 / Demande','services.request.title':'Dites-moi ce dont vous avez besoin.','services.request.intro':'Choisissez le type d’accompagnement qui vous intéresse et donnez-moi suffisamment de contexte pour comprendre votre situation.','services.direct':'Ou contactez-moi directement :',
'form.name':'Nom complet','form.email':'Email','form.phone':'Numéro WhatsApp','form.profile':'Votre profil','form.select':'Sélectionner','form.service':'Que recherchez-vous ?','form.domain':'Votre domaine / secteur','form.goals':'Que souhaitez-vous améliorer ou résoudre ?','form.submit':'Envoyer la demande','footer.right':'Réalisé en HTML, CSS & JavaScript'
}};
document.querySelectorAll('[data-i18n]').forEach(e=>e.dataset.enText=e.innerHTML);
function setLanguage(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;e.innerHTML=lang==='fr'&&translations.fr[k]?translations.fr[k]:e.dataset.enText});languageButtons.forEach(b=>{const a=b.dataset.lang===lang;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});localStorage.setItem('language',lang)}
function updateThemeButton(){const isDark=root.dataset.theme==='dark';toggle.setAttribute('aria-pressed',String(isDark));toggle.setAttribute('aria-label',isDark?'Switch to light mode':'Switch to dark mode');toggle.querySelector('.theme-label').textContent=isDark?'Light':'Dark';if(themeColor)themeColor.setAttribute('content',isDark?'#111315':'#fbfbf9')}
updateThemeButton();toggle.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('theme',root.dataset.theme);updateThemeButton()});languageButtons.forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));setLanguage(localStorage.getItem('language')||'en');